service: edwincruz-app

plugins:
  - serverless-apigw-binary
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 30


package:
  exclude:
    - ./**
  include:
    - "node_modules/@vendia/**"
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
    - "lambda.js"

custom:
  apigwBinary:
    types:
      - '*/*'

functions:
  api:
    handler: lambda.handler
    events:
      - http: GET /
      - http: GET /{proxy+}
